import type { AppStore } from "@/lib/types";

const now = new Date().toISOString();

export const seedStore: AppStore = {
  services: [
    {
      slug: "house-wash",
      name: "House wash",
      shortName: "House",
      description: "Soft wash for siding, soffits, trim, and normal organic growth.",
      quoteMode: "instant",
      unit: "per_1000_sqft",
      unitLabel: "1,000 sqft",
      sizeLabel: "Home size",
      sizeOptions: [
        { label: "Small", value: 1500, description: "Under 1,800 sqft" },
        { label: "Standard", value: 2500, description: "1,800-3,000 sqft" },
        { label: "Large", value: 3500, description: "3,000-4,200 sqft" },
        { label: "Estate", value: 5000, description: "4,200+ sqft" },
      ],
    },
    {
      slug: "window-cleaning",
      name: "Window cleaning",
      shortName: "Windows",
      description: "Exterior or full window cleaning with screens/tracks scoped separately.",
      quoteMode: "instant",
      unit: "per_window",
      unitLabel: "window",
      sizeLabel: "Window count",
      sizeOptions: [
        { label: "Light", value: 20, description: "Up to 20 windows" },
        { label: "Standard", value: 35, description: "21-35 windows" },
        { label: "Large", value: 55, description: "36-55 windows" },
        { label: "Estate", value: 80, description: "56+ windows" },
      ],
    },
    {
      slug: "roof-wash",
      name: "Roof wash",
      shortName: "Roof",
      description: "Soft wash roof treatment with plant protection and runoff planning.",
      quoteMode: "review_required",
      unit: "per_1000_sqft",
      unitLabel: "1,000 sqft",
      sizeLabel: "Roof/home size",
      sizeOptions: [
        { label: "Small", value: 1500, description: "Under 1,800 sqft" },
        { label: "Standard", value: 2500, description: "1,800-3,000 sqft" },
        { label: "Large", value: 3500, description: "3,000-4,200 sqft" },
        { label: "Estate", value: 5000, description: "4,200+ sqft" },
      ],
    },
    {
      slug: "gutters",
      name: "Gutter cleanout",
      shortName: "Gutters",
      description: "Gutter cleanout priced by linear footage, height, and guard complexity.",
      quoteMode: "instant",
      unit: "per_100_linear_ft",
      unitLabel: "100 linear ft",
      sizeLabel: "Gutter length",
      sizeOptions: [
        { label: "Small", value: 100, description: "Up to 100 linear ft" },
        { label: "Standard", value: 150, description: "100-175 linear ft" },
        { label: "Large", value: 250, description: "175-300 linear ft" },
        { label: "Estate", value: 350, description: "300+ linear ft" },
      ],
    },
    {
      slug: "patio-wash",
      name: "Patio / walkway wash",
      shortName: "Patio",
      description: "Surface cleaning for patios, walkways, pool decks, and small flatwork.",
      quoteMode: "instant",
      unit: "per_100_sqft",
      unitLabel: "100 sqft",
      sizeLabel: "Patio / walkway area",
      sizeOptions: [
        { label: "Small", value: 200, description: "Up to 200 sqft" },
        { label: "Standard", value: 400, description: "200-500 sqft" },
        { label: "Large", value: 700, description: "500-850 sqft" },
        { label: "Estate", value: 1000, description: "850+ sqft" },
      ],
    },
    {
      slug: "fence-wash",
      name: "Fence wash",
      shortName: "Fence",
      description: "Fence washing by linear footage, height, sides, material, and condition.",
      quoteMode: "instant",
      unit: "per_100_linear_ft",
      unitLabel: "100 linear ft",
      sizeLabel: "Fence length",
      sizeOptions: [
        { label: "Small", value: 100, description: "Up to 100 linear ft" },
        { label: "Standard", value: 200, description: "100-225 linear ft" },
        { label: "Large", value: 300, description: "225-350 linear ft" },
        { label: "Estate", value: 500, description: "350+ linear ft" },
      ],
    },
    {
      slug: "paver-refresh",
      name: "Paver refresh",
      shortName: "Pavers",
      description: "Paver cleaning intake with restoration, sanding, and sealing separated.",
      quoteMode: "review_required",
      unit: "per_100_sqft",
      unitLabel: "100 sqft",
      sizeLabel: "Paver area",
      sizeOptions: [
        { label: "Small", value: 300, description: "Up to 300 sqft" },
        { label: "Standard", value: 600, description: "300-750 sqft" },
        { label: "Large", value: 1000, description: "750-1,200 sqft" },
        { label: "Estate", value: 1500, description: "1,200+ sqft" },
      ],
    },
    {
      slug: "solar-panels",
      name: "Solar panel cleaning",
      shortName: "Solar",
      description: "Solar panel cleaning by panel count and roof/access conditions.",
      quoteMode: "instant",
      unit: "per_panel",
      unitLabel: "panel",
      sizeLabel: "Panel count",
      sizeOptions: [
        { label: "Small", value: 12, description: "Up to 12 panels" },
        { label: "Standard", value: 24, description: "13-24 panels" },
        { label: "Large", value: 36, description: "25-36 panels" },
        { label: "Estate", value: 48, description: "37+ panels" },
      ],
    },
    {
      slug: "permanent-lighting",
      name: "Permanent lighting",
      shortName: "Lighting",
      description: "Permanent lighting lead intake with install survey and deposit planning.",
      quoteMode: "survey_required",
      unit: "flat",
      unitLabel: "project",
      sizeLabel: "Project size",
      sizeOptions: [
        { label: "Entry", value: 1, description: "Front roofline only" },
        { label: "Standard", value: 2, description: "Front and sides" },
        { label: "Large", value: 3, description: "Multi-zone install" },
        { label: "Estate", value: 4, description: "Large custom project" },
      ],
    },
    {
      slug: "painting",
      name: "Painting lead",
      shortName: "Painting",
      description: "Painting lead intake for exterior/interior scope review.",
      quoteMode: "survey_required",
      unit: "flat",
      unitLabel: "project",
      sizeLabel: "Project size",
      sizeOptions: [
        { label: "Touch-up", value: 1, description: "Small touch-up area" },
        { label: "Room/section", value: 2, description: "One room or exterior section" },
        { label: "Large", value: 3, description: "Multiple rooms or large exterior section" },
        { label: "Full project", value: 4, description: "Whole home or complex project" },
      ],
    },
  ],
  costInputs: [
    {
      serviceSlug: "house-wash",
      hourlyLaborRate: 42,
      materialCostPerUnit: 40,
      equipmentWearPerHour: 8,
      hoursPerUnit: 1.6,
      driveReserveMinutes: 30,
      overheadPct: 0.15,
      minMarginPct: 0.3,
      serviceMinimum: 350,
      depositThreshold: 900,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "window-cleaning",
      hourlyLaborRate: 42,
      materialCostPerUnit: 0.5,
      equipmentWearPerHour: 4,
      hoursPerUnit: 0.033,
      driveReserveMinutes: 30,
      overheadPct: 0.15,
      minMarginPct: 0.3,
      serviceMinimum: 225,
      depositThreshold: 750,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "roof-wash",
      hourlyLaborRate: 42,
      materialCostPerUnit: 65,
      equipmentWearPerHour: 12,
      hoursPerUnit: 2.2,
      driveReserveMinutes: 40,
      overheadPct: 0.15,
      minMarginPct: 0.35,
      serviceMinimum: 650,
      depositThreshold: 900,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "gutters",
      hourlyLaborRate: 42,
      materialCostPerUnit: 4,
      equipmentWearPerHour: 6,
      hoursPerUnit: 0.85,
      driveReserveMinutes: 30,
      overheadPct: 0.15,
      minMarginPct: 0.3,
      serviceMinimum: 225,
      depositThreshold: 750,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "patio-wash",
      hourlyLaborRate: 42,
      materialCostPerUnit: 6,
      equipmentWearPerHour: 8,
      hoursPerUnit: 0.32,
      driveReserveMinutes: 30,
      overheadPct: 0.15,
      minMarginPct: 0.3,
      serviceMinimum: 225,
      depositThreshold: 800,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "fence-wash",
      hourlyLaborRate: 42,
      materialCostPerUnit: 10,
      equipmentWearPerHour: 8,
      hoursPerUnit: 0.85,
      driveReserveMinutes: 35,
      overheadPct: 0.15,
      minMarginPct: 0.32,
      serviceMinimum: 275,
      depositThreshold: 900,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "paver-refresh",
      hourlyLaborRate: 42,
      materialCostPerUnit: 18,
      equipmentWearPerHour: 12,
      hoursPerUnit: 0.55,
      driveReserveMinutes: 40,
      overheadPct: 0.16,
      minMarginPct: 0.36,
      serviceMinimum: 500,
      depositThreshold: 850,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "solar-panels",
      hourlyLaborRate: 42,
      materialCostPerUnit: 1.5,
      equipmentWearPerHour: 5,
      hoursPerUnit: 0.06,
      driveReserveMinutes: 30,
      overheadPct: 0.15,
      minMarginPct: 0.3,
      serviceMinimum: 225,
      depositThreshold: 750,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "permanent-lighting",
      hourlyLaborRate: 48,
      materialCostPerUnit: 950,
      equipmentWearPerHour: 12,
      hoursPerUnit: 5.5,
      driveReserveMinutes: 45,
      overheadPct: 0.18,
      minMarginPct: 0.38,
      serviceMinimum: 900,
      depositThreshold: 900,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
    {
      serviceSlug: "painting",
      hourlyLaborRate: 48,
      materialCostPerUnit: 450,
      equipmentWearPerHour: 8,
      hoursPerUnit: 4,
      driveReserveMinutes: 45,
      overheadPct: 0.18,
      minMarginPct: 0.35,
      serviceMinimum: 750,
      depositThreshold: 900,
      bufferActive: true,
      source: "industry_default",
      updatedAt: now,
    },
  ],
  competitorPrices: [
    {
      id: "cp_001",
      serviceSlug: "house-wash",
      competitorName: "Window Hero Huntington",
      zipOrRegion: "11743",
      priceLow: 375,
      priceMedian: 525,
      priceHigh: 700,
      unit: "standard home",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_002",
      serviceSlug: "house-wash",
      competitorName: "Ro-Flow Exterior Cleaning",
      zipOrRegion: "Suffolk County",
      priceLow: 350,
      priceMedian: 500,
      priceHigh: 725,
      unit: "standard home",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_003",
      serviceSlug: "house-wash",
      competitorName: "Elite Power Cleaning",
      zipOrRegion: "Long Island",
      priceLow: 325,
      priceMedian: 475,
      priceHigh: 650,
      unit: "standard home",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_004",
      serviceSlug: "house-wash",
      competitorName: "Regional exterior cleaning median",
      zipOrRegion: "Nassau County",
      priceLow: 375,
      priceMedian: 550,
      priceHigh: 750,
      unit: "standard home",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_005",
      serviceSlug: "window-cleaning",
      competitorName: "Window Hero Huntington",
      zipOrRegion: "11743",
      priceLow: 250,
      priceMedian: 375,
      priceHigh: 550,
      unit: "35 windows",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_006",
      serviceSlug: "window-cleaning",
      competitorName: "Long Island window cleaning median",
      zipOrRegion: "Long Island",
      priceLow: 225,
      priceMedian: 350,
      priceHigh: 525,
      unit: "35 windows",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_007",
      serviceSlug: "window-cleaning",
      competitorName: "Nassau residential window median",
      zipOrRegion: "Nassau County",
      priceLow: 275,
      priceMedian: 425,
      priceHigh: 625,
      unit: "35 windows",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_008",
      serviceSlug: "roof-wash",
      competitorName: "Suffolk soft wash median",
      zipOrRegion: "Suffolk County",
      priceLow: 575,
      priceMedian: 825,
      priceHigh: 1200,
      unit: "standard roof",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_009",
      serviceSlug: "roof-wash",
      competitorName: "Nassau soft wash median",
      zipOrRegion: "Nassau County",
      priceLow: 650,
      priceMedian: 900,
      priceHigh: 1350,
      unit: "standard roof",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
    {
      id: "cp_010",
      serviceSlug: "roof-wash",
      competitorName: "Long Island roof wash median",
      zipOrRegion: "Long Island",
      priceLow: 600,
      priceMedian: 850,
      priceHigh: 1250,
      unit: "standard roof",
      sourceUrl: "manual observation",
      observedDate: "2026-05-07",
    },
  ],
  quotes: [],
  outcomes: [],
  decisionLog: [
    {
      id: "dl_001",
      event: "V1 scope locked to deterministic pricing",
      evidence:
        "User-approved v3 plan cut AI, demographics, scrapers, Clerk/deed lookup, Web Push, and invoice PDFs from V1.",
      nextReview: "After first live quote",
      createdAt: now,
    },
    {
      id: "dl_002",
      event: "Nassau enrichment treated as optional",
      evidence:
        "NYS public parcel service lists Suffolk as public-shareable; Nassau was not listed in the current public layer.",
      nextReview: "After truth gate script runs on 15 LI addresses",
      createdAt: now,
    },
  ],
};
